# Site settings
title: Pilates on Druid Hill
email: pilatesondruidhill@gmail.com
email_subject: new client
description: > # this means to ignore newlines until "baseurl:"
    Classical Pilates Reformer, Tower, Chair & Mat
    Private Pilates sessions at an affordable price
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# Build settings
markdown: kramdown
exclude: [README.md, assets, package.json, npmfile.js, gulpfile.js, Gemfile, Gemfile.lock, LICENSE, node_modules]